name: Setup cyborg environment
description: Setup cyborg environment for checking PRs

runs:
  using: composite
  steps:
    # 1. Кешируем ~/.pnpm-store и node_modules между запусками
    - name: Cache pnpm store and node_modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.pnpm-store
          cyborg/node_modules
        key: ${{ runner.os }}-pnpm-${{ hashFiles('cyborg/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    # 2. Устанавливаем Node.js LTS
    - uses: actions/setup-node@v4
      with:
        node-version: "18" # или '16' — предпочтительно LTS
        cache: "pnpm" # чтобы pnpm кешировался автоматически

    # 3. Устанавливаем pnpm и зависимости
    - uses: pnpm/action-setup@v3
      with:
        version: 8 # зафиксировать нужную версию pnpm
        run_install: true
        working-directory: cyborg

    # 4. Проверяем, что всё установилось
    - name: Describe the Environment
      working-directory: cyborg
      shell: bash
      run: |
        echo "Node: $(node -v)"
        echo "pnpm: $(pnpm -v)"
        pnpm tsx -v
