blank_issues_enabled: false
contact_links:
  - name: Zumic Community Pachca
    url: https://app.pachca.com/join?invite_token=EakW3nIgma_ezqFc&company_name=Zumic+Community&company_id=416542
    about: Get free help from the Zumic community
  - name: Zumic Community Discussion
    url: https://github.com/zumicTeam/discussions
    about: Get free help from the Zumic community
