name: Enhancement
description: Suggest an enhancement to existing functionality
labels: ["enhancement"]
body:
  - type: dropdown
    id: type
    attributes:
      label: What type of enhancement is this?
      multiple: true
      options:
        - API improvement
        - Configuration
        - Performance
        - Refactor
        - Tech debt reduction
        - User experience
        - Other

  - type: textarea
    id: what
    attributes:
      label: What does the enhancement do?
      description: |
        Give a high-level overview of how you
        suggest improving an existing feature or functionality.

  - type: textarea
    id: implementation
    attributes:
      label: Implementation ideas or challenges
      description: |
        Share any ideas of how to implement the enhancement, or what could be difficult.
