name: New Feature
description: Suggest a new feature for Zumic
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template to suggest a completely new feature for Zumic.
        If you want to propose an improvement to an existing feature, please use the "Enhancement" template.
        For bug reports, use the bug report template.

  - type: textarea
    id: problem
    attributes:
      label: What problem does this feature solve?
      description: |
        Clearly describe the problem or need that this new feature would address.
        Why is it important to add this feature to Zumic?
        Did you consider alternative solutions outside of Zumic?
    # required: true  # Можно добавить, если хочешь сделать поле обязательным

  - type: textarea
    id: feature
    attributes:
      label: What does the feature do?
      description: |
        Give a high-level overview of what the feature should do and how it might work in Zumic.
    # required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation ideas or challenges
      description: |
        If you have thoughts on how to implement the feature, or foresee any particular challenges, describe them here.
    # required: false
