name: Upload artifacts
description: Upload specified files into an archive, compute sha256 and upload both artifacts.

inputs:
  artifacts-dir:
    description: Directory to store artifacts (relative to working-dir)
    required: true
  target-files:
    description: Comma-separated list of files/paths to copy into artifacts-dir (optional)
    required: false
    default: ""
  version:
    description: Version of the artifact (used in filenames)
    required: true
  working-dir:
    description: Working directory where files are located
    required: false
    default: "."
  retention-days:
    description: Retention days for uploaded artifacts
    required: false
    default: "7"
  archive-prefix:
    description: Optional prefix to put before archive filename (e.g. 'zumic')
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Prepare artifacts directory (copy target files when provided)
      working-directory: ${{ inputs.working-dir }}
      shell: bash
      run: |
        set -euo pipefail
        ART_DIR="${{ inputs.artifacts-dir }}"
        mkdir -p "${ART_DIR}"

        if [ -n "${{ inputs.target-files }}" ]; then
          IFS=',' read -ra FILES <<< "${{ inputs.target-files }}"
          for file in "${FILES[@]}"; do
            # trim spaces
            file="$(echo "$file" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
            if [ -z "$file" ]; then
              continue
            fi
            if [ -e "$file" ]; then
              cp -r "$file" "${ART_DIR}/" || true
            else
              echo "warning: target file not found: $file"
            fi
          done
        else
          echo "no target-files specified — assuming outputs already in ${ART_DIR}"
        fi

    - name: Create archive + checksum (safe copy to temp to avoid 'file changed' race)
      working-directory: ${{ inputs.working-dir }}
      shell: bash
      id: create
      run: |
        set -euo pipefail

        ART_DIR="${{ inputs.artifacts-dir }}"
        VERSION="${{ inputs.version }}"
        PREFIX="${{ inputs.archive-prefix }}"

        # Decide base name
        if [ -n "${PREFIX}" ]; then
          BASE="${PREFIX}-${VERSION}"
        else
          CLEAN_ART_DIR=$(basename "${ART_DIR%/}")
          BASE="${CLEAN_ART_DIR}-${VERSION}"
        fi

        ARCHIVE_NAME="${BASE}.tar.gz"
        SHA_NAME="${BASE}.sha256sum"

        echo "Archiving '${ART_DIR}' -> ${ARCHIVE_NAME} (via temporary copy)..."

        TMPDIR="$(mktemp -d)"
        # copy contents (preserve attributes where possible); ignore errors copying ephemeral things
        cp -a "${ART_DIR}/." "${TMPDIR}/" || true

        # create archive from tmpdir to avoid "file changed as we read it"
        tar -C "${TMPDIR}" -czf "${ARCHIVE_NAME}" .
        # compute checksum
        if command -v shasum >/dev/null 2>&1; then
          shasum -a 256 "${ARCHIVE_NAME}" | awk '{print $1}' > "${SHA_NAME}"
        else
          sha256sum "${ARCHIVE_NAME}" | awk '{print $1}' > "${SHA_NAME}"
        fi

        # move outputs to working dir (so later upload path is predictable)
        mv -f "${ARCHIVE_NAME}" "${{ inputs.working-dir }}/" || true
        mv -f "${SHA_NAME}" "${{ inputs.working-dir }}/" || true

        # cleanup
        rm -rf "${TMPDIR}"

        echo "Created files: ${ARCHIVE_NAME} ${SHA_NAME}"
        # export outputs for later steps
        echo "ARCHIVE_NAME=${ARCHIVE_NAME}" >> $GITHUB_OUTPUT
        echo "SHA_NAME=${SHA_NAME}" >> $GITHUB_OUTPUT

    - name: Upload archive artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.create.outputs.ARCHIVE_NAME }}
        path: ${{ inputs.working-dir }}/${{ steps.create.outputs.ARCHIVE_NAME }}
        retention-days: ${{ inputs.retention-days }}

    - name: Upload checksum artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.create.outputs.SHA_NAME }}
        path: ${{ inputs.working-dir }}/${{ steps.create.outputs.SHA_NAME }}
        retention-days: ${{ inputs.retention-days }}
