[profile.default]
# Настройка таймаута для "медленных" тестов:
# - если тест выполняется дольше `period`, будет предпринята
# попытка завершения.
# - если тест не завершится в течение `grace-period`, он будет
# принудительно завершён.
# - если такое происходит `terminate-after` раз — тест считается
# проваленным.
slow-timeout = { period = "60s", terminate-after = 3, grace-period = "30s" }

# Повторное выполнение тестов при неудаче:
# - count: максимальное число повторов (3 раза)
# - delay: начальная задержка между попытками (10 секунд)
# - backoff: тип увеличения задержки (экспоненциальный рост)
# - jitter: добавляет случайный разброс в задержку (для предотвращения
# "толчков")
retries = { backoff = "exponential", count = 3, delay = "10s", jitter = true }
