name: Development Build

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      skip_tests:
        description: "Skip tests"
        type: boolean
        default: true
      profile:
        description: "Cargo profile"
        type: choice
        options:
          - dev
          - release
          - nightly
        default: dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ inputs.profile }}
          profile: ${{ inputs.profile }}
          override: true

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Lint with Clippy
        run: cargo clippy --all-targets --all-features

      - name: Build
        run: |
          if [ "${{ inputs.profile }}" = "release" ]; then
            cargo build --release
          elif [ "${{ inputs.profile }}" = "nightly" ]; then
            cargo +nightly build
          else
            cargo build
          fi

      - name: Run tests
        if: ${{ !inputs.skip_tests }}
        run: |
          if [ "${{ inputs.profile }}" = "release" ]; then
            cargo test --release
          elif [ "${{ inputs.profile }}" = "nightly" ]; then
            cargo +nightly test
          else
            cargo test
          fi

      - name: Run tests
        if: ${{ !inputs.skip_tests }}
        run: |
          if [ "${{ inputs.profile }}" = "release" ]; then
            cargo test --release
          elif [ "${{ inputs.profile }}" = "nightly" ]; then
            cargo +nightly test
          else
            cargo test
          fi
