name: Development Build

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      skip_tests:
        description: "Skip tests"
        type: boolean
        default: true
      profile:
        description: "Cargo profile"
        type: choice
        options: [dev, release, nightly]
        default: dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # По умолчанию проверяет текущий коммит, ref указывать не нужно

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust@v1
        with:
          profile: ${{ inputs.profile }}

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Lint with Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build
        run: cargo build --${{ inputs.profile }}

      - name: Run tests
        if: ${{ !inputs.skip_tests }}
        run: cargo test --${{ inputs.profile }}
