name: Semantic Pull Request

on:
  pull_request:
    types: [opened, reopened, edited]
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate PR title/message
        run: echo "🔎 PR follows semantic guidelines"
